// Alias for the getcar command
COMMAND:getvehicle(playerid, params[]) 
    return cmd_getcar(playerid, params);

// Alias for the rentcar command
COMMAND:rentvehicle(playerid, params[]) 
    return cmd_rentcar(playerid, params);

// Alias for the work command
COMMAND:duty(playerid, params[]) 
    return cmd_work(playerid, params);

// Alias for the stopwork command
COMMAND:endwork(playerid, params[]) 
    return cmd_stopwork(playerid, params);

// Alias for cleanupcar command
COMMAND:delvehicle(playerid, params[])
    return cmd_cleanupcar(playerid, params);

// Alias for fuel command
COMMAND:refill(playerid, params[]) 
    return cmd_fuel(playerid, params);

// Alias for fly command
COMMAND:jetpack(playerid, params[]) 
    return cmd_fly(playerid, params);

// Alias for cmds command
COMMAND:commands(playerid, params[]) 
    return cmd_cmds(playerid, params);

// Alias for givecash command
COMMAND:givemoney(playerid, params[]) 
    return cmd_givecash(playerid, params);

// Alias for report command
COMMAND:complain(playerid, params[]) 
    return cmd_report(playerid, params);

// Alias for rep command
COMMAND:complaints(playerid, params[]) 
    return cmd_rep(playerid, params);

// Aliases for changepassword command
COMMAND:changepass(playerid, params[]) 
    return cmd_changepassword(playerid, params);

COMMAND:changepw(playerid, params[]) 
    return cmd_changepassword(playerid, params);

COMMAND:password(playerid, params[]) 
    return cmd_changepassword(playerid, params);

// Alias for announce command
COMMAND:annn(playerid, params[]) 
    return cmd_announce(playerid, params);

// Alias for fuelall command
COMMAND:refillall(playerid, params[]) 
    return cmd_fuelall(playerid, params);

// Alias for createspike command
COMMAND:spike(playerid, params[])
    return cmd_createspike(playerid, params);

// Alias for gobase command
COMMAND:rescue(playerid, params[])
    return cmd_gobase(playerid, params);

// Alias for cleanupvehicle command
COMMAND:cleanupcar(playerid, params[])
    return cmd_cleanupvehicle(playerid, params);

