// COMMAND:NEW(playerid, params[]) return cmd_OLD(playerid, params); // Alias for /OLD
COMMAND:ann(playerid, params[]) return cmd_announce(playerid, params); // Alias for /announce
COMMAND:asay(playerid, params[]) return cmd_achat(playerid, params); // Alias for /asay
COMMAND:changepass(playerid, params[]) return cmd_changepassword(playerid, params); // Aliases for /changepassword
COMMAND:changepw(playerid, params[]) return cmd_changepassword(playerid, params); // Aliases for /changepassword
COMMAND:cleanupcar(playerid, params[]) return cmd_cleanupvehicle(playerid, params); // Alias for /cleanupvehicle
COMMAND:cleanupcars(playerid, params[]) return cmd_cleanupallvehicles(playerid, params); // Alias for /cleanupallvehicles
COMMAND:commands(playerid, params[]) return cmd_cmds(playerid, params); // Alias for /cmds
COMMAND:complain(playerid, params[]) return cmd_report(playerid, params); // Alias for /report
COMMAND:complaints(playerid, params[]) return cmd_rep(playerid, params); // Alias for /rep
COMMAND:delvehicle(playerid, params[]) return cmd_cleanupcar(playerid, params); // Alias for /cleanupcar
COMMAND:duty(playerid, params[]) return cmd_work(playerid, params); // Alias for the /work
COMMAND:endwork(playerid, params[]) return cmd_stopwork(playerid, params); // Alias for the /stopwork
COMMAND:getvehicle(playerid, params[]) return cmd_getcar(playerid, params); // Alias for the /getcar
COMMAND:givemoney(playerid, params[]) return cmd_givecash(playerid, params); // Alias for /givecash
COMMAND:jetpack(playerid, params[]) return cmd_fly(playerid, params); // Alias for /fly
COMMAND:mutes(playerid, params[]) return cmd_muted(playerid, params); // Alias for /muted
COMMAND:object(playerid, params[]) return cmd_createobject(playerid, params); // Alias for /createobject
COMMAND:password(playerid, params[]) return cmd_changepassword(playerid, params); // Aliases for /changepassword
COMMAND:pickup(playerid, params[]) return cmd_createpickup(playerid, params); // Alias for /createpickup
COMMAND:refill(playerid, params[]) return cmd_fuel(playerid, params); // Alias for /fuel
COMMAND:refillall(playerid, params[]) return cmd_fuelall(playerid, params); // Alias for /fuelall
COMMAND:rentvehicle(playerid, params[]) return cmd_rentcar(playerid, params); // Alias for the /rentcar
COMMAND:rescue(playerid, params[]) return cmd_gobase(playerid, params); // Alias for /gobase
COMMAND:respawn(playerid, params[]) return cmd_respawnvehicle(playerid, params); // Alias for /respawnvehicle
COMMAND:say(playerid, params[]) return cmd_radio(playerid, params); // Alias for /say
COMMAND:spike(playerid, params[]) return cmd_createspike(playerid, params); // Alias for /createspike
COMMAND:vehicle(playerid, params[]) return cmd_createvehicle(playerid, params); // Alias for /vehicle
COMMAND:wanted(playerid, params[]) return cmd_setwanted(playerid, params); // Alias for /setwanted