// COMMAND:NEW(playerid, params[]) return cmd_OLD(playerid, params); // Alias for /OLD
COMMAND:ann(playerid, params[]) return cmd_announce(playerid, params); // Alias for /announce
COMMAND:commands(playerid, params[]) return cmd_cmds(playerid, params); // Alias for /cmds
COMMAND:complain(playerid, params[]) return cmd_report(playerid, params); // Alias for /report
COMMAND:complaints(playerid, params[]) return cmd_reports(playerid, params); // Alias for /reports
COMMAND:gc(playerid, params[]) return cmd_givecash(playerid, params); // Alias for /givecash
COMMAND:m(playerid, params[]) return cmd_pm(playerid, params); // Alias for /pm